version: "3.9"

services:
  postgres:
    image: postgres:15
    container_name: postgres_lab_junior
    environment:
      POSTGRES_USER: dba
      POSTGRES_PASSWORD: dba123
      POSTGRES_DB: labdb
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
